version: '2.38.2'
services:
  frotnend:
    container_name: frontend-4mm
    build: .
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./:/frontend
      - /frontend/node_modules
